// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmKtMxlKGCGjDkFYkGj_tm7wNs4u_IDIY',
    appId: '1:610360715147:web:16cdda01d4345e6a24f18e',
    messagingSenderId: '610360715147',
    projectId: 'billingmedical-e5a25',
    authDomain: 'billingmedical-e5a25.firebaseapp.com',
    storageBucket: 'billingmedical-e5a25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3_n8wf-uLPSir9Mhf-GCo9UJp4x6oi4',
    appId: '1:610360715147:android:71422a9006b4ccea24f18e',
    messagingSenderId: '610360715147',
    projectId: 'billingmedical-e5a25',
    storageBucket: 'billingmedical-e5a25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXHdNV6op9SYki9RDEa489lkLdqcmCy2w',
    appId: '1:610360715147:ios:b843f4a203efebf024f18e',
    messagingSenderId: '610360715147',
    projectId: 'billingmedical-e5a25',
    storageBucket: 'billingmedical-e5a25.appspot.com',
    iosClientId: '610360715147-7baf0kthhbldbakhge01023855592807.apps.googleusercontent.com',
    iosBundleId: 'com.example.billingmedical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXHdNV6op9SYki9RDEa489lkLdqcmCy2w',
    appId: '1:610360715147:ios:b843f4a203efebf024f18e',
    messagingSenderId: '610360715147',
    projectId: 'billingmedical-e5a25',
    storageBucket: 'billingmedical-e5a25.appspot.com',
    iosClientId: '610360715147-7baf0kthhbldbakhge01023855592807.apps.googleusercontent.com',
    iosBundleId: 'com.example.billingmedical',
  );
}
